services:
  # ----------------------------
  # MongoDB Service
  # ----------------------------
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: djsdev
      MONGO_INITDB_DATABASE: GDASH
    ports:
      - "27015:27017"
    volumes:
      - /data/db